# This script converts a VCF generated by varscan to a tsv comparable to tsv output of this
# variant caller.
# It doesn't have any sanity checks, it is NOT written for long sustinability
# If it shows that VC works, it might not, if it shows it doesn't work, it still might.
BEGIN{
    print("CHROM\tPOS\tREF\tALT\tFC\tSC\tPC\tDP\tQDP")
}

{
    if ($1~"^#") 
    {
        next
    }
    else 
    {
        printf $1
        printf "\t"
        printf $2
        printf "\t"
        printf $4
        printf "\t"
        printf $5
        printf "\t"
        split($10   , INFO, ":")
        printf INFO[13]
        printf "\t"
        printf INFO[14]
        printf "\t"
        printf "."
        printf "\t"
        printf INFO[3]
        printf "\t"
        printf INFO[4]
        printf "\n"

    }
}