import sys
import os
#This is pretty:
def compare(right: list, my_texts: list) -> bool:
    """compares the right text to texts given by our cvc

    Parameters
    ----------
    text : list of string
        line from tsv by varscan
    my_texts : list of lists of strings
        all lines for given position given by our cvc
    """
    if len(my_texts) == 0:
        return False
    for my in my_texts:
        if (my[0] == right[0] and my[1] == right[1] and my[2] == right[2] and my[3] == right[3]):
            return True
    return False

#This is a little bit ugly
if len(sys.argv)==1 or sys.argv[1] == "-h" or sys.argv[1] == "--help" :
    print("\n  Compare tsv generated by CVC with tsv generated by Varscan and varscanVcf2tsv.awk")
    print("  Before calling this script, sort both files by `sort -k2 -t \t -n`")
    print("    Usage: python3 test.py [cvc.tsv] [varscan.tsv]\n")
    exit(0)

my_name = sys.argv[1]
right_name = sys.argv[2]

print(f"Comparing {my_name} with {right_name}")

# This is getting more ugly...
my = open(my_name, "r")
right = open(right_name, "r")
right.readline()
my_text = my.readline().split('\t')

success = 0
failure = 0
grep_passes = 0

for line in right:
    text = line.split('\t')
    while (my_text[0] == text[0] and my_text[1] < text[1]) or (my_text[0] < text[0]): 
        # Yes we really want to compare strings, because bash-sort sorts as strings
        my_text = my.readline().split('\t')
    
    if my_text[1] == text[1]:
        my_texts = []
        while my_text[1] == text[1]:
            my_texts.append(my_text)
            my_text = my.readline().split('\t')
        if (compare(text, my_texts)):
            success += 1
        else:
            failure += 1
            print(f"{my_texts} doesn't match {text}")
    # This wasn't so bad, was it? At least it made some sence...
    # Now brace yourselves!

    else:
        froms_grep = os.popen(f"grep '{text[1]}' {my_name}").read().split('\n')
        # Wow! This is ugly, it just calls the bash `grep` command on the whole file!
        # Then splits it into single lines
        # This is because I don't want to solve why some variants are wrongly skipped...
        # If you want to redo it -> have fun!
        found = False
        for from_grep_txt in froms_grep[:-1]:
            from_grep = from_grep_txt.split('\t')
            # Now every line is split into lists like before, ok?
            if from_grep[0] == text[0] and from_grep[1] == text[1] and from_grep[2] == text[2] and from_grep[3] == text[3]:
                # This if just says if the are equal in the important columns.
                found=True
                break

        if found:
            grep_passes+=1
        else:
            failure += 1
            print(f"No match for {text}")

# You made it through! This is just some printing at the end!
print(f"failures: {failure}")
print(f"grep passes: {grep_passes}")
print(f"successes: {success}")

if (failure):
    print("\nE: DIFFERENCES FOUND!")
else:
    print("\nFiles match!")

my.close()
right.close()


